#!/bin/bash
#SBATCH -J half
#SBATCH -t 04:55:00
#SBATCH -N 1
#SBATCH --mem=16G
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=4

module load 2023
module load 2024
module load Python/3.10.4-GCCcore-11.3.0
module load Anaconda3/2024.06-1
module load CUDA/12.1.1
module load TensorFlow/2.15.1-foss-2023a-CUDA-12.1.1
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1


source activate GraphCast
cd /home/mvaznonis

python half.py